/* Synthetic policy only. No host APIs, network tunnel, or enforcement. */
(function(g){'use strict';
const capability=Object.freeze({antivirus:'not-connected',firewall:'host-status-unknown',vpn:'unavailable-in-this-browser',enforcement:false});
function classify(flow){if(!flow||!['tcp','udp'].includes(flow.proto)||!['in','out'].includes(flow.direction)||!['new','established'].includes(flow.state)||!['public','private','domain'].includes(flow.profile)||!Number.isInteger(flow.dst_port)||flow.dst_port<1||flow.dst_port>65535)throw Error('Choose a valid protocol, direction, connection state, profile, and port (1–65535).');
let action,rule;if(flow.direction==='out'&&flow.proto==='tcp'&&flow.dst_port===445){action='deny';rule='demo-deny-smb-out';}else if(flow.state==='established'){action='allow';rule='demo-established-reply';}else if(flow.direction==='in'){action='deny';rule='demo-default-inbound-deny';}else{action='allow';rule='demo-default-outbound-allow';}
return {action,rule,scenario:{...flow},applied:false,host_status:'unknown',note:'Synthetic example only. Connection state is supplied, not observed. Profiles are recorded but this demo uses the same rules for all profiles. Real Windows policy also depends on application, service, addresses, rule precedence, and managed policy.'};}
function endpoint(value){if(typeof value!=='string'||value.length>253||!value||value!==value.trim()||/[\s/@?#\\]/.test(value))throw Error('Use hostname:port or [IPv6]:port, without credentials or a URL.');const m=value.match(/^(\[[0-9a-fA-F:]+\]|[a-zA-Z0-9.-]+):(\d{1,5})$/);if(!m||Number(m[2])<1||Number(m[2])>65535)throw Error('Endpoint needs a port from 1 to 65535.');if(!m[1].startsWith('[')&&m[1].split('.').some(v=>!v||v.length>63||!/^[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(v)))throw Error('Invalid hostname.');try{new URL('https://'+value);}catch(e){throw Error('Invalid endpoint address.');}return value;}
function vpnPlan(cfg){if(!cfg||!['wireguard-plan','ikev2-plan'].includes(cfg.mode))throw Error('Select a supported planning mode.');const target=endpoint(cfg.endpoint);if(typeof cfg.dns!=='string'||!cfg.dns||/[\s/?#@\\]/.test(cfg.dns)||cfg.dns.includes('%'))throw Error('Enter one DNS IP address.');const dns=cfg.dns;if(dns.includes(':')){try{const u=new URL('https://['+dns+']/');if(!u.hostname.startsWith('['))throw Error();}catch(e){throw Error('Invalid DNS IPv6 address.');}}else if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(dns)||dns.split('.').some(n=>Number(n)>255||(n.length>1&&n.startsWith('0'))))throw Error('Invalid DNS IPv4 address.');
return {configuration_valid:true,mode:cfg.mode,endpoint:target,dns,state:capability.vpn,connected:false,applied:false,handshake:'not-tested',routing:'not-tested',dns_leaks:'not-tested',kill_switch:'not-implemented',requires:['A separate supported device/client','Peer or provider configuration','Keys kept outside this website','Routing, DNS and failure-path verification'],note:'Format validation only. Reachability, ownership, credentials and actual protection are not verified.'};}
g.MantisPlans={capability,classify,vpnPlan};
})(globalThis);
