(function(g){'use strict';
function summarize(d){if(!d||typeof d!=='object'||Array.isArray(d))throw Error('Report must be a JSON object.');const schema=d.schema;let metrics={};
if(schema==='aethera-health-export/v1'){if(!Array.isArray(d.pages)||d.pages.some(p=>!p||!Array.isArray(p.issues)))throw Error('Invalid health report.');metrics.pages=d.pages.length;metrics.activeIssues=d.pages.reduce((n,p)=>n+p.issues.filter(i=>i&&i.active===true).length,0);metrics.stalePages=d.pages.filter(p=>Number.isFinite(p.at)&&Date.now()-p.at>120000).length;}
else if(schema==='aethera-game-design-handoff/v1'||schema==='aethera-game-learning/v1'){const m=d.learning||d;if(!m||!m.stats||typeof m.stats!=='object'||Array.isArray(m.stats))throw Error('Invalid learning report.');let help=0,fun=0;for(const v of Object.values(m.stats)){if(!v||!['helpYes','helpNo','funYes','funNo'].every(k=>Number.isSafeInteger(v[k])&&v[k]>=0&&v[k]<=100000))throw Error('Invalid rating counts.');help+=v.helpYes;fun+=v.funYes;}metrics.helpfulRatings=help;metrics.funRatings=fun;metrics.learningContexts=Object.keys(m.stats).length;}
else if(schema==='aethera-iterations/v1'){if(!Array.isArray(d.results)||d.results.some(r=>!r||typeof r.blocked!=='boolean'||!Number.isFinite(r.max)||r.max<0||r.max>1))throw Error('Invalid iteration results.');metrics.completedSets=d.results.length;metrics.blockedSets=d.results.filter(r=>r.blocked).length;metrics.maxRisk=d.results.length?Math.max(...d.results.map(r=>r.max)):0;}
else if(schema==='aethera-save-export/v1'){if(!Array.isArray(d.records)||d.records.some(r=>!r||r.schema!=='aethera-save/v1'||typeof r.id!=='string'))throw Error('Invalid save export.');metrics.saveRecords=d.records.length;}
else throw Error('Unsupported report type. Choose an Aethera health, learning, iteration, or save export.');
return {schema,metrics,evidence:'user-supplied; not independently verified'};}
function compare(a,b){if(a.schema!==b.schema)throw Error('Choose two reports with the same schema.');return Object.keys(a.metrics).map(k=>({metric:k,before:a.metrics[k],after:b.metrics[k],difference:b.metrics[k]-a.metrics[k]}));}
function suggest(r){const m=r.metrics;if(m.activeIssues>0)return 'Reproduce one active issue in Firefox, make one isolated fix, then export a new health report. Treat stale tabs separately from failures.';if(m.blockedSets>0)return 'Review the blocked risk axes and original inputs. Fix the underlying issue, then rerun the same scenario. Do not lower scores merely to clear the gate.';if('funRatings'in m)return m.funRatings===0?'Play one mechanic and explicitly rate whether it was fun. Do not infer enjoyment from completion.':'Compare a clue with a direct answer on the same mechanic, then collect explicit helpfulness and fun ratings.';if('saveRecords'in m)return 'Use a test save, reload the same game in Firefox, and compare the scene and inventory. Export a backup first.';return 'Run one repeatable browser scenario and collect a second report. No recorded issue is not proof that every feature works.';}
g.OnyxCore={summarize,compare,suggest};})(globalThis);
